/* tslint:disable */
/* eslint-disable */
/**
 * Appei
 * API of Appetee Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Diet } from '../models';
import { Param } from '../../environement/envdev';
import { QueryReturn } from '../models';
/**
 * DietApi - axios parameter creator
 * @export
 */
export const DietApiAxiosParamCreator = function (configuration?: Configuration) {
    console.log("fourth DietGet");
    return {
        /**
         * Test
         * @summary Delete diet object
         * @param {number} dietId The Id of a diet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dietDietIdDelete: async (dietId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'dietId' is not null or undefined
            if (dietId === null || dietId === undefined) {
                throw new RequiredError('dietId','Required parameter dietId was null or undefined when calling dietDietIdDelete.');
            }
            const localVarPath = `/diet/{diet_id}/`
                .replace(`{${"diet_id"}}`, encodeURIComponent(String(dietId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(Param.baseUrl);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }

            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarPath,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test
         * @summary Retrieve a diet object
         * @param {number} dietId The Id of a diet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dietDietIdGet: async (dietId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'dietId' is not null or undefined
            if (dietId === null || dietId === undefined) {
                throw new RequiredError('dietId','Required parameter dietId was null or undefined when calling dietDietIdGet.');
            }
            const localVarPath = `/diet/{diet_id}/`
                .replace(`{${"diet_id"}}`, encodeURIComponent(String(dietId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(Param.baseUrl);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarPath,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test
         * @summary Update diet object
         * @param {Diet} body 
         * @param {number} dietId The Id of a diet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dietDietIdPatch: async (body: Diet, dietId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling dietDietIdPatch.');
            }
            // verify required parameter 'dietId' is not null or undefined
            if (dietId === null || dietId === undefined) {
                throw new RequiredError('dietId','Required parameter dietId was null or undefined when calling dietDietIdPatch.');
            }
            const localVarPath = `/diet/{diet_id}/`
                .replace(`{${"diet_id"}}`, encodeURIComponent(String(dietId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of diets
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dietGet: async (offset?: number, limit?: number, options: any = {}): Promise<RequestArgs> => {
            console.log("fourth DietGet");
            const localVarPath = `/diet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            let localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            console.log("five DietGet");
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            console.log("six DietGet");
            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            
            console.log(localVarHeaderParameter["API-KEY"]);
            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }
            
            console.log("seven DietGet");
            //const query = new URLSearchParams(Param.baseUrl);
            const query = new URLSearchParams(Param.baseUrl);
            console.log("seven DietGet");
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            console.log("height DietGet");
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            console.log("nine DietGet");
            //localVarUrlObj.search = (new URLSearchParams(query)).toString();
            //let test2 = (new URLSearchParams(query)).toString();
            //console.log(test2);
            console.log(options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            console.log(localVarRequestOptions.headers);
            return {
                url:  localVarPath,//localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a diet
         * @param {Diet} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dietPost: async (body: Diet, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling dietPost.');
            }
            const localVarPath = `/diet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            let localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(Param.baseUrl);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            //localVarUrlObj.search = (new URLSearchParams(query)).toString();
            console.log(query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarPath ,//localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DietApi - functional programming interface
 * @export
 */
export const DietApiFp = function(configuration?: Configuration) {
    console.log("second DietGet");
    return {
        /**
         * Test
         * @summary Delete diet object
         * @param {number} dietId The Id of a diet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dietDietIdDelete(dietId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Diet>> {
            const localVarAxiosArgs = await DietApiAxiosParamCreator(configuration).dietDietIdDelete(dietId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test
         * @summary Retrieve a diet object
         * @param {number} dietId The Id of a diet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dietDietIdGet(dietId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Diet>> {
            const localVarAxiosArgs = await DietApiAxiosParamCreator(configuration).dietDietIdGet(dietId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test
         * @summary Update diet object
         * @param {Diet} body 
         * @param {number} dietId The Id of a diet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dietDietIdPatch(body: Diet, dietId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Diet>> {
            const localVarAxiosArgs = await DietApiAxiosParamCreator(configuration).dietDietIdPatch(body, dietId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of diets
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dietGet(offset?: number, limit?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Diet>>> {
            const localVarAxiosArgs = await DietApiAxiosParamCreator(configuration).dietGet(offset, limit, options);
            console.log("4 DietGet");
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                console.log("5 DietGet");
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create a diet
         * @param {Diet} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dietPost(body: Diet, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Diet>> {
            const localVarAxiosArgs = await DietApiAxiosParamCreator(configuration).dietPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DietApi - factory interface
 * @export
 */
export const DietApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Test
         * @summary Delete diet object
         * @param {number} dietId The Id of a diet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dietDietIdDelete(dietId: number, options?: any): AxiosPromise<Diet> {
            return DietApiFp(configuration).dietDietIdDelete(dietId, options).then((request) => request(axios, basePath));
        },
        /**
         * Test
         * @summary Retrieve a diet object
         * @param {number} dietId The Id of a diet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dietDietIdGet(dietId: number, options?: any): AxiosPromise<Diet> {
            return DietApiFp(configuration).dietDietIdGet(dietId, options).then((request) => request(axios, basePath));
        },
        /**
         * Test
         * @summary Update diet object
         * @param {Diet} body 
         * @param {number} dietId The Id of a diet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dietDietIdPatch(body: Diet, dietId: number, options?: any): AxiosPromise<Diet> {
            return DietApiFp(configuration).dietDietIdPatch(body, dietId, options).then((request) => request(axios, basePath));
        },
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of diets
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dietGet(offset?: number, limit?: number, options?: any): AxiosPromise<Array<Diet>> {
            return DietApiFp(configuration).dietGet(offset, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a diet
         * @param {Diet} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dietPost(body: Diet, options?: any): AxiosPromise<Diet> {
            return DietApiFp(configuration).dietPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DietApi - object-oriented interface
 * @export
 * @class DietApi
 * @extends {BaseAPI}
 */
export class DietApi extends BaseAPI {
    /**
     * Test
     * @summary Delete diet object
     * @param {number} dietId The Id of a diet
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DietApi
     */
    public dietDietIdDelete(dietId: number, options?: any) {
        return DietApiFp(this.configuration).dietDietIdDelete(dietId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test
     * @summary Retrieve a diet object
     * @param {number} dietId The Id of a diet
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DietApi
     */
    public dietDietIdGet(dietId: number, options?: any) {
        return DietApiFp(this.configuration).dietDietIdGet(dietId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test
     * @summary Update diet object
     * @param {Diet} body 
     * @param {number} dietId The Id of a diet
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DietApi
     */
    public dietDietIdPatch(body: Diet, dietId: number, options?: any) {
        return DietApiFp(this.configuration).dietDietIdPatch(body, dietId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This operation supports pagination
     * @summary Retrieve a collection of diets
     * @param {number} [offset] The number of items to skip before returning the results
     * @param {number} [limit] The number of items to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DietApi
     */
    public dietGet(offset?: number, limit?: number, options?: any) {
        return DietApiFp(this.configuration).dietGet(offset, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create a diet
     * @param {Diet} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DietApi
     */
    public dietPost(body: Diet, options?: any) {
        return DietApiFp(this.configuration).dietPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
