/* tslint:disable */
/* eslint-disable */
/**
 * Appei
 * API of Appetee Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { IngredientInRecepies } from '../models';
/**
 * IngredientInRecepiesApi - axios parameter creator
 * @export
 */
export const IngredientInRecepiesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of ingredient_in_recepies
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientInRecepiesGet: async (offset?: number, limit?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/ingredient_in_recepies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IngredientInRecepiesApi - functional programming interface
 * @export
 */
export const IngredientInRecepiesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of ingredient_in_recepies
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingredientInRecepiesGet(offset?: number, limit?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await IngredientInRecepiesApiAxiosParamCreator(configuration).ingredientInRecepiesGet(offset, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * IngredientInRecepiesApi - factory interface
 * @export
 */
export const IngredientInRecepiesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of ingredient_in_recepies
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientInRecepiesGet(offset?: number, limit?: number, options?: any): AxiosPromise<void> {
            return IngredientInRecepiesApiFp(configuration).ingredientInRecepiesGet(offset, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IngredientInRecepiesApi - object-oriented interface
 * @export
 * @class IngredientInRecepiesApi
 * @extends {BaseAPI}
 */
export class IngredientInRecepiesApi extends BaseAPI {
    /**
     * This operation supports pagination
     * @summary Retrieve a collection of ingredient_in_recepies
     * @param {number} [offset] The number of items to skip before returning the results
     * @param {number} [limit] The number of items to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngredientInRecepiesApi
     */
    public ingredientInRecepiesGet(offset?: number, limit?: number, options?: any) {
        return IngredientInRecepiesApiFp(this.configuration).ingredientInRecepiesGet(offset, limit, options).then((request) => request(this.axios, this.basePath));
    }
}
