/* tslint:disable */
/* eslint-disable */
/**
 * Appei
 * API of Appetee Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Ingredients } from '../models';
import { Param } from '../../environement/envdev';
import { QueryReturn } from '../models';
/**
 * IngredientsApi - axios parameter creator
 * @export
 */
export const IngredientsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of ingredients objects
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientsGet: async (offset?: number, limit?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/ingredients`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(Param.baseUrl);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarPath,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test
         * @summary Delete ingredients object
         * @param {number} ingredientsId The Id of a ingredient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientsIngredientsIdDelete: async (ingredientsId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'ingredientsId' is not null or undefined
            if (ingredientsId === null || ingredientsId === undefined) {
                throw new RequiredError('ingredientsId','Required parameter ingredientsId was null or undefined when calling ingredientsIngredientsIdDelete.');
            }
            const localVarPath = `/ingredients/{ingredients_id}/`
                .replace(`{${"ingredients_id"}}`, encodeURIComponent(String(ingredientsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test
         * @summary Retrieve a ingredient object
         * @param {number} ingredientsId The Id of a ingredient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientsIngredientsIdGet: async (ingredientsId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'ingredientsId' is not null or undefined
            if (ingredientsId === null || ingredientsId === undefined) {
                throw new RequiredError('ingredientsId','Required parameter ingredientsId was null or undefined when calling ingredientsIngredientsIdGet.');
            }
            const localVarPath = `/ingredients/{ingredients_id}/`
                .replace(`{${"ingredients_id"}}`, encodeURIComponent(String(ingredientsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test
         * @summary Update ingredients object
         * @param {Ingredients} body 
         * @param {number} ingredientsId The Id of a ingredient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientsIngredientsIdPatch: async (body: Ingredients, ingredientsId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling ingredientsIngredientsIdPatch.');
            }
            // verify required parameter 'ingredientsId' is not null or undefined
            if (ingredientsId === null || ingredientsId === undefined) {
                throw new RequiredError('ingredientsId','Required parameter ingredientsId was null or undefined when calling ingredientsIngredientsIdPatch.');
            }
            const localVarPath = `/ingredients/{ingredients_id}/`
                .replace(`{${"ingredients_id"}}`, encodeURIComponent(String(ingredientsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create ingredients
         * @param {Ingredients} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientsPost: async (body: Ingredients, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling ingredientsPost.');
            }
            const localVarPath = `/ingredients`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IngredientsApi - functional programming interface
 * @export
 */
export const IngredientsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of ingredients objects
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingredientsGet(offset?: number, limit?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Ingredients>>> {
            const localVarAxiosArgs = await IngredientsApiAxiosParamCreator(configuration).ingredientsGet(offset, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test
         * @summary Delete ingredients object
         * @param {number} ingredientsId The Id of a ingredient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingredientsIngredientsIdDelete(ingredientsId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await IngredientsApiAxiosParamCreator(configuration).ingredientsIngredientsIdDelete(ingredientsId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test
         * @summary Retrieve a ingredient object
         * @param {number} ingredientsId The Id of a ingredient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingredientsIngredientsIdGet(ingredientsId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Ingredients>> {
            const localVarAxiosArgs = await IngredientsApiAxiosParamCreator(configuration).ingredientsIngredientsIdGet(ingredientsId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test
         * @summary Update ingredients object
         * @param {Ingredients} body 
         * @param {number} ingredientsId The Id of a ingredient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingredientsIngredientsIdPatch(body: Ingredients, ingredientsId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await IngredientsApiAxiosParamCreator(configuration).ingredientsIngredientsIdPatch(body, ingredientsId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create ingredients
         * @param {Ingredients} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ingredientsPost(body: Ingredients, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await IngredientsApiAxiosParamCreator(configuration).ingredientsPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * IngredientsApi - factory interface
 * @export
 */
export const IngredientsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of ingredients objects
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientsGet(offset?: number, limit?: number, options?: any): AxiosPromise<Array<Ingredients>> {
            return IngredientsApiFp(configuration).ingredientsGet(offset, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Test
         * @summary Delete ingredients object
         * @param {number} ingredientsId The Id of a ingredient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientsIngredientsIdDelete(ingredientsId: number, options?: any): AxiosPromise<void> {
            return IngredientsApiFp(configuration).ingredientsIngredientsIdDelete(ingredientsId, options).then((request) => request(axios, basePath));
        },
        /**
         * Test
         * @summary Retrieve a ingredient object
         * @param {number} ingredientsId The Id of a ingredient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientsIngredientsIdGet(ingredientsId: number, options?: any): AxiosPromise<Ingredients> {
            return IngredientsApiFp(configuration).ingredientsIngredientsIdGet(ingredientsId, options).then((request) => request(axios, basePath));
        },
        /**
         * Test
         * @summary Update ingredients object
         * @param {Ingredients} body 
         * @param {number} ingredientsId The Id of a ingredient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientsIngredientsIdPatch(body: Ingredients, ingredientsId: number, options?: any): AxiosPromise<void> {
            return IngredientsApiFp(configuration).ingredientsIngredientsIdPatch(body, ingredientsId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create ingredients
         * @param {Ingredients} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ingredientsPost(body: Ingredients, options?: any): AxiosPromise<void> {
            return IngredientsApiFp(configuration).ingredientsPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IngredientsApi - object-oriented interface
 * @export
 * @class IngredientsApi
 * @extends {BaseAPI}
 */
export class IngredientsApi extends BaseAPI {
    /**
     * This operation supports pagination
     * @summary Retrieve a collection of ingredients objects
     * @param {number} [offset] The number of items to skip before returning the results
     * @param {number} [limit] The number of items to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngredientsApi
     */
    public ingredientsGet(offset?: number, limit?: number, options?: any) {
        return IngredientsApiFp(this.configuration).ingredientsGet(offset, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test
     * @summary Delete ingredients object
     * @param {number} ingredientsId The Id of a ingredient
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngredientsApi
     */
    public ingredientsIngredientsIdDelete(ingredientsId: number, options?: any) {
        return IngredientsApiFp(this.configuration).ingredientsIngredientsIdDelete(ingredientsId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test
     * @summary Retrieve a ingredient object
     * @param {number} ingredientsId The Id of a ingredient
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngredientsApi
     */
    public ingredientsIngredientsIdGet(ingredientsId: number, options?: any) {
        return IngredientsApiFp(this.configuration).ingredientsIngredientsIdGet(ingredientsId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test
     * @summary Update ingredients object
     * @param {Ingredients} body 
     * @param {number} ingredientsId The Id of a ingredient
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngredientsApi
     */
    public ingredientsIngredientsIdPatch(body: Ingredients, ingredientsId: number, options?: any) {
        return IngredientsApiFp(this.configuration).ingredientsIngredientsIdPatch(body, ingredientsId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create ingredients
     * @param {Ingredients} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngredientsApi
     */
    public ingredientsPost(body: Ingredients, options?: any) {
        return IngredientsApiFp(this.configuration).ingredientsPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
