/* tslint:disable */
/* eslint-disable */
/**
 * Appei
 * API of Appetee Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { QueryReturn } from '../models';
import { Recipes } from '../models';
/**
 * RecipesApi - axios parameter creator
 * @export
 */
export const RecipesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of recipe objects
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeGet: async (offset?: number, limit?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/recipe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create recipes
         * @param {Recipes} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipePost: async (body: Recipes, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling recipePost.');
            }
            const localVarPath = `/recipe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test
         * @summary Delete ingredients object
         * @param {number} recipeId The Id of a recipe
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeRecipeIdDelete: async (recipeId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'recipeId' is not null or undefined
            if (recipeId === null || recipeId === undefined) {
                throw new RequiredError('recipeId','Required parameter recipeId was null or undefined when calling recipeRecipeIdDelete.');
            }
            const localVarPath = `/recipe/{recipe_id}/`
                .replace(`{${"recipe_id"}}`, encodeURIComponent(String(recipeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test
         * @summary Retrieve a ingredient object
         * @param {number} recipeId The Id of a recipe
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeRecipeIdGet: async (recipeId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'recipeId' is not null or undefined
            if (recipeId === null || recipeId === undefined) {
                throw new RequiredError('recipeId','Required parameter recipeId was null or undefined when calling recipeRecipeIdGet.');
            }
            const localVarPath = `/recipe/{recipe_id}/`
                .replace(`{${"recipe_id"}}`, encodeURIComponent(String(recipeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test
         * @summary Update recipe object
         * @param {Recipes} body 
         * @param {number} recipeId The Id of a recipe
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeRecipeIdPatch: async (body: Recipes, recipeId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling recipeRecipeIdPatch.');
            }
            // verify required parameter 'recipeId' is not null or undefined
            if (recipeId === null || recipeId === undefined) {
                throw new RequiredError('recipeId','Required parameter recipeId was null or undefined when calling recipeRecipeIdPatch.');
            }
            const localVarPath = `/recipe/{recipe_id}/`
                .replace(`{${"recipe_id"}}`, encodeURIComponent(String(recipeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecipesApi - functional programming interface
 * @export
 */
export const RecipesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of recipe objects
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipeGet(offset?: number, limit?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Recipes>>> {
            const localVarAxiosArgs = await RecipesApiAxiosParamCreator(configuration).recipeGet(offset, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create recipes
         * @param {Recipes} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipePost(body: Recipes, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await RecipesApiAxiosParamCreator(configuration).recipePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test
         * @summary Delete ingredients object
         * @param {number} recipeId The Id of a recipe
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipeRecipeIdDelete(recipeId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await RecipesApiAxiosParamCreator(configuration).recipeRecipeIdDelete(recipeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test
         * @summary Retrieve a ingredient object
         * @param {number} recipeId The Id of a recipe
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipeRecipeIdGet(recipeId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Recipes>> {
            const localVarAxiosArgs = await RecipesApiAxiosParamCreator(configuration).recipeRecipeIdGet(recipeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test
         * @summary Update recipe object
         * @param {Recipes} body 
         * @param {number} recipeId The Id of a recipe
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recipeRecipeIdPatch(body: Recipes, recipeId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await RecipesApiAxiosParamCreator(configuration).recipeRecipeIdPatch(body, recipeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RecipesApi - factory interface
 * @export
 */
export const RecipesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of recipe objects
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeGet(offset?: number, limit?: number, options?: any): AxiosPromise<Array<Recipes>> {
            return RecipesApiFp(configuration).recipeGet(offset, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create recipes
         * @param {Recipes} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipePost(body: Recipes, options?: any): AxiosPromise<void> {
            return RecipesApiFp(configuration).recipePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Test
         * @summary Delete ingredients object
         * @param {number} recipeId The Id of a recipe
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeRecipeIdDelete(recipeId: number, options?: any): AxiosPromise<void> {
            return RecipesApiFp(configuration).recipeRecipeIdDelete(recipeId, options).then((request) => request(axios, basePath));
        },
        /**
         * Test
         * @summary Retrieve a ingredient object
         * @param {number} recipeId The Id of a recipe
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeRecipeIdGet(recipeId: number, options?: any): AxiosPromise<Recipes> {
            return RecipesApiFp(configuration).recipeRecipeIdGet(recipeId, options).then((request) => request(axios, basePath));
        },
        /**
         * Test
         * @summary Update recipe object
         * @param {Recipes} body 
         * @param {number} recipeId The Id of a recipe
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recipeRecipeIdPatch(body: Recipes, recipeId: number, options?: any): AxiosPromise<void> {
            return RecipesApiFp(configuration).recipeRecipeIdPatch(body, recipeId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecipesApi - object-oriented interface
 * @export
 * @class RecipesApi
 * @extends {BaseAPI}
 */
export class RecipesApi extends BaseAPI {
    /**
     * This operation supports pagination
     * @summary Retrieve a collection of recipe objects
     * @param {number} [offset] The number of items to skip before returning the results
     * @param {number} [limit] The number of items to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public recipeGet(offset?: number, limit?: number, options?: any) {
        return RecipesApiFp(this.configuration).recipeGet(offset, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create recipes
     * @param {Recipes} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public recipePost(body: Recipes, options?: any) {
        return RecipesApiFp(this.configuration).recipePost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test
     * @summary Delete ingredients object
     * @param {number} recipeId The Id of a recipe
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public recipeRecipeIdDelete(recipeId: number, options?: any) {
        return RecipesApiFp(this.configuration).recipeRecipeIdDelete(recipeId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test
     * @summary Retrieve a ingredient object
     * @param {number} recipeId The Id of a recipe
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public recipeRecipeIdGet(recipeId: number, options?: any) {
        return RecipesApiFp(this.configuration).recipeRecipeIdGet(recipeId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test
     * @summary Update recipe object
     * @param {Recipes} body 
     * @param {number} recipeId The Id of a recipe
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecipesApi
     */
    public recipeRecipeIdPatch(body: Recipes, recipeId: number, options?: any) {
        return RecipesApiFp(this.configuration).recipeRecipeIdPatch(body, recipeId, options).then((request) => request(this.axios, this.basePath));
    }
}
