/* tslint:disable */
/* eslint-disable */
/**
 * Appei
 * API of Appetee Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { QueryReturn } from '../models';
import { Recipes } from '../models';
import { User } from '../models';
import { Param } from '../../environement/envdev';
/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of user objects
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userGet: async (offset?: number, limit?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test
         * @summary Retrieve a user object
         * @param {Array&lt;number&gt;} usersId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userGetrecepesUsersIdGet: async (usersId: Array<number>, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'usersId' is not null or undefined
            if (usersId === null || usersId === undefined) {
                throw new RequiredError('usersId','Required parameter usersId was null or undefined when calling userGetrecepesUsersIdGet.');
            }
            const localVarPath = `/user/getrecepes/{users_id}`
                .replace(`{${"users_id"}}`, encodeURIComponent(String(usersId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary update user Info
         * @param {User} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userPost: async (body: User, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling userPost.');
            }
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(Param.baseUrl);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarPath,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test
         * @summary Delete ingredients object
         * @param {number} userId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userUserIdDelete: async (userId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling userUserIdDelete.');
            }
            const localVarPath = `/user/{user_id}/`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Test
         * @summary Retrieve a user object
         * @param {number} userId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userUserIdGet: async (userId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling userUserIdGet.');
            }
            const localVarPath = `/user/{user_id}/`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * update
         * @summary Update user object
         * @param {User} body 
         * @param {number} userId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userUserIdPatch: async (body: User, userId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling userUserIdPatch.');
            }
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling userUserIdPatch.');
            }
            const localVarPath = `/user/{user_id}/`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("API-KEY")
                    : await configuration.apiKey;
                localVarHeaderParameter["API-KEY"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of user objects
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userGet(offset?: number, limit?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<User>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userGet(offset, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test
         * @summary Retrieve a user object
         * @param {Array&lt;number&gt;} usersId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userGetrecepesUsersIdGet(usersId: Array<number>, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Recipes>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userGetrecepesUsersIdGet(usersId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary update user Info
         * @param {User} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userPost(body: User, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<QueryReturn>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test
         * @summary Delete ingredients object
         * @param {number} userId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userUserIdDelete(userId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userUserIdDelete(userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Test
         * @summary Retrieve a user object
         * @param {number} userId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userUserIdGet(userId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<User>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userUserIdGet(userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * update
         * @summary Update user object
         * @param {User} body 
         * @param {number} userId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userUserIdPatch(body: User, userId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userUserIdPatch(body, userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * This operation supports pagination
         * @summary Retrieve a collection of user objects
         * @param {number} [offset] The number of items to skip before returning the results
         * @param {number} [limit] The number of items to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userGet(offset?: number, limit?: number, options?: any): AxiosPromise<Array<User>> {
            return UserApiFp(configuration).userGet(offset, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Test
         * @summary Retrieve a user object
         * @param {Array&lt;number&gt;} usersId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userGetrecepesUsersIdGet(usersId: Array<number>, options?: any): AxiosPromise<Array<Recipes>> {
            return UserApiFp(configuration).userGetrecepesUsersIdGet(usersId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary update user Info
         * @param {User} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userPost(body: User, options?: any): AxiosPromise<Array<QueryReturn>> {
            return UserApiFp(configuration).userPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Test
         * @summary Delete ingredients object
         * @param {number} userId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userUserIdDelete(userId: number, options?: any): AxiosPromise<void> {
            return UserApiFp(configuration).userUserIdDelete(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Test
         * @summary Retrieve a user object
         * @param {number} userId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userUserIdGet(userId: number, options?: any): AxiosPromise<Array<User>> {
            return UserApiFp(configuration).userUserIdGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * update
         * @summary Update user object
         * @param {User} body 
         * @param {number} userId The Id of a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userUserIdPatch(body: User, userId: number, options?: any): AxiosPromise<void> {
            return UserApiFp(configuration).userUserIdPatch(body, userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * This operation supports pagination
     * @summary Retrieve a collection of user objects
     * @param {number} [offset] The number of items to skip before returning the results
     * @param {number} [limit] The number of items to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userGet(offset?: number, limit?: number, options?: any) {
        return UserApiFp(this.configuration).userGet(offset, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test
     * @summary Retrieve a user object
     * @param {Array&lt;number&gt;} usersId The Id of a user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userGetrecepesUsersIdGet(usersId: Array<number>, options?: any) {
        return UserApiFp(this.configuration).userGetrecepesUsersIdGet(usersId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary update user Info
     * @param {User} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userPost(body: User, options?: any) {
        return UserApiFp(this.configuration).userPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test
     * @summary Delete ingredients object
     * @param {number} userId The Id of a user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userUserIdDelete(userId: number, options?: any) {
        return UserApiFp(this.configuration).userUserIdDelete(userId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Test
     * @summary Retrieve a user object
     * @param {number} userId The Id of a user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userUserIdGet(userId: number, options?: any) {
        return UserApiFp(this.configuration).userUserIdGet(userId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * update
     * @summary Update user object
     * @param {User} body 
     * @param {number} userId The Id of a user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userUserIdPatch(body: User, userId: number, options?: any) {
        return UserApiFp(this.configuration).userUserIdPatch(body, userId, options).then((request) => request(this.axios, this.basePath));
    }
}
