/* tslint:disable */
/* eslint-disable */
/**
 * Appei
 * API of Appetee Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Authentification
 */
export interface Authentification {
    /**
     * 
     * @type {string}
     * @memberof Authentification
     */
    session_cookie: any;
    /**
     * 
     * @type {number}
     * @memberof Authentification
     */
    user_id: any;
}
