/* tslint:disable */
/* eslint-disable */
/**
 * Appei
 * API of Appetee Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IngredientInRecepies
 */
export interface IngredientInRecepies {
    /**
     * 
     * @type {string}
     * @memberof IngredientInRecepies
     */
    quantite: any;
    /**
     * 
     * @type {boolean}
     * @memberof IngredientInRecepies
     */
    optional: any;
    /**
     * 
     * @type {string}
     * @memberof IngredientInRecepies
     */
    comment?: any;
    /**
     * 
     * @type {Ingredients}
     * @memberof IngredientInRecepies
     */
    ingredient: any;
}
