/* tslint:disable */
/* eslint-disable */
/**
 * Appei
 * API of Appetee Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Recipes
 */
export interface Recipes {
    /**
     * 
     * @type {number}
     * @memberof Recipes
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Recipes
     */
    nom: any;
    /**
     * 
     * @type {number}
     * @memberof Recipes
     */
    temps: any;
    /**
     * 
     * @type {number}
     * @memberof Recipes
     */
     nb_person: any;
    /**
     * 
     * @type {string}
     * @memberof Recipes
     */
     image_recipes_url?: any;
    /**
     * 
     * @type {string}
     * @memberof Recipes
     */
    directions: any;
    /**
     * 
     * @type {string}
     * @memberof Recipes
     */
    tag?: any;
    /**
     * 
     * @type {Array&lt;Diet&gt;}
     * @memberof Recipes
     */
    diets?: any;
    /**
     * 
     * @type {Array&lt;IngredientInRecepies&gt;}
     * @memberof Recipes
     */
    ingredients?: any;
}
