/* tslint:disable */
/* eslint-disable */
/**
 * Appei
 * API of Appetee Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/auth-api';
export * from './apis/diet-api';
export * from './apis/ingredient-in-recepies-api';
export * from './apis/ingredients-api';
export * from './apis/recipes-api';
export * from './apis/user-api';

